# name: Publish to npm
# on:
#   release:
#     types: [published]
# jobs:
#   publish-to-npm:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read
#       id-token: write
#     steps:
#       - uses: actions/checkout@v4
#       - uses: actions/setup-node@v4
#         with:
#           node-version: 24.x
#           registry-url: https://registry.npmjs.org
#       - run: npm run publish:npm
#         env:
#           NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
#   publish-to-jsr:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read
#       id-token: write
#     steps:
#       - uses: actions/checkout@v4
#       - uses: denoland/setup-deno@v2
#         with:
#           deno-version: v2.x
#       - run: deno task publish:jsr
name: Publish

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: npm install

      - name: Extract version and changelog content
        id: changelog
        run: node scripts/extract-changelog.ts

      - name: Get package name
        id: package
        run: echo "PACKAGE_NAME=$(jq -r .name package.json)" >> $GITHUB_OUTPUT

      # - name: Determine if pre-release
      #   id: prerelease
      #   run: |
      #     if [[ "${{ steps.changelog.outputs.version }}" == *-* ]]; then
      #       echo "IS_PRERELEASE=true" >> $GITHUB_OUTPUT
      #     else
      #       echo "IS_PRERELEASE=false" >> $GITHUB_OUTPUT
      #     fi

      - name: Publish to npm
        run: |
          if [ "${{ steps.changelog.outputs.IS_PRERELEASE }}" == "true" ]; then
            npm run publish:npm --tag next
          else
            npm run publish:npm
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to JSR
        run: npm run publish:jsr

      - name: Set newest tag
        run: npm dist-tag add ${{ steps.package.outputs.PACKAGE_NAME }}@${{ steps.changelog.outputs.VERSION }} newest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          # tag_name: v${{ steps.changelog.outputs.VERSION }}
          name: v${{ steps.changelog.outputs.VERSION }}
          body: ${{ steps.changelog.outputs.CONTENT }}
          prerelease: ${{ steps.changelog.outputs.IS_PRERELEASE }}
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}